# Hello, and welcome to the Phrase Randomiser.
# This simple script exists to take a whole load of phrases and memes and randomly choose them.
# This is basically me playing around with lists and the random library to see what I can do while learning Python.
# This collection of memes, phrases, and slogans can (and likely will) be very handy for some, so please feel free to copy this code or add to it :3
# One thing you can use this for is to pipe it into cowsay (or simular) with "<path to this script>/phraserandomiser.py | cowsay"
# Anyway, have fun, contribute more at https://github.com/abbiistabbii/pythonscripts/blob/main/phraserandomiser.py!

import random

phraselist = ["Master Skywalker, did you know that in terms of human pokemon breeding...",
"NOTHING BEATS A JET2 HOLIDAY!",
"You truly are the King of Kings.",
"Well there's no cock like Horse Cock!",
"Emacs cured my Autism!",
"Nice Cock!",
"Cunty Buttlicks!",
"Arsebiscuits!",
"hewo...mimster obabnab?",
"DO I LOOK LIKE SOMEONE WHO CARES WHAT GOD THINKS?",
"YOUR NAME SHALL ALSO GO ON ZE LIST, WHAT IS IT?",
"I BLAME SOCIETY!",
"owo what's this?",
"God has let me live another day and I am going to make that everyone else's problem",
"Thanks! I hate this!",
"FUCK YOU I LOVE THIS!",
"uwu kimochiiiiii~",
"We have to steal the Declaration of Independence",
"What hath God wrought?",
"Epstein didn't kill himself",
"No Gods, No Masters",
"No Balls, No Masters!",
"Gun Diathan, Gun Tigheran!",
"As fearr Gaidhlig briste na Gaidhlig anns a chiste!",
"I've...seen things you people wouldn't believe",
"Fuck the OSA!",
"Something something Daaaaaaaaaark Siiiiiiiiiiide something",
"In the poop? In the poop.",
"FUCK ME YOURSELF YOU FUCKING COWARD",
"Except the Shrimp",
"Remember kids, Woke is literally just a relabeling of the word 'Degenerate' as the Nazis used it in the 1930s!",
"BANG! AND THE DIRT IS GONE!",
"Never gonna give you up, never gonna let you down...",
"Come to the Brian the Manwhore Memorial!",
"WELCOME TO THE PISS ZONE!",
"The law is on the books, but it would take all their resources to enforce it!",
"Free Palestine, Free Tibet.",
"Fuck Vladimir Putin!",
"Fuck Donald Trump!",
"Trans rights!",
"Trans Rights are Human Rights",
"Fuck TERFS and SWERFS",
"God may love you but Satan does that thing with his tongue owo",
"Everyday I'm suffering! AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"Hail Linus!",
"Gonnae no dae that",
"Milk Lemonaid Chocolate!",
"You have been doing this for a while, aye?",
"From the moment I understood the weakness of my flesh, it disgusted me. I craved the strength and certainty of steel.",
"owo",
"uwu",
"BLOOD FOR THE BLOOD GOD!",
"SKULLS FOR THE SKULL THRONE!",
"MILK FOR THE CORNFLAKES!",
"PISS FOR THE PISS JUG!",
"Glory, Glory tae the Hibees! Glory, Glory tae the Hibees! Glory Glory tae the Hibees, they are the Hibee bois!",
"Be Gay, Do Crime!",
"Bi gèidh, dean eucoirean!",
"Fuck Keir Starmer the Queer Harmer",
"Fuck Anti Queer Keir",
"MILF: Man I love Frogs",
"WHY ARE YOU GETTING CLOTHES FROM THE SOUP STORE?!",
"Do you know what C Equals?",
"Aurora Borealis? At this time of year! At this time of day! In this part of the country! Localized entirely within your kitchen?!?",
"According to all known laws of aviation, there is no way a bee should be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of course, flies anyway because bees don't care what humans think is impossible.",
"I am going to punch your face...in the face",
"I like trains.",
"Morse Pacman also eats dashes",
"Any joke is a one-liner if your page is wide enough",
"If you say slurs in front of your pets when they die they'll inform the universe and you will be punished for it",
"On the internet, no-one can hear you unless you buy a bunch of bots to artificially amplify your reach",
"You should stop noticing the frames of your glasses right now",
"Baby carrots aren't even made out of babies",
"Be they, do crime",
"I'm not sure if hot air baloons and blimps are friends but I think they should be",
"Does going through the washing machine feel like a spa day for our towels?",
"Who made it a rule that we're supposed to answer our front door when it gets knocked on unannounced? And how am I the asshole as the knockee ignoring you and not you as the knocker who showed up out of nowhere?",
"The smaller the spoon, the smaller the portion, but also, the smaller the spoon the higher the chance a big spoon will hug you",
"This is the 88th line of this document and quite frankly I'm suspicious of its political views",
"Having an air fryer is not a personality",
"Having a waffle iron is absolutely a personality",
"The existence of GITHub infers the existence of GITSpokes",
"Does GITHub have a GITSpokesperson?",
"Wait, so this doesn't get installed in my butt? Ohhhhh, it's not a supository it's a repository. But surely you can put it on a flash drive with a flared base tho...",
"The worst thing about being a people pleaser is you're people too, but rarely do people please you",
"If your wanted a red shirt instead of a blue shirt just run away super fast from whomever is criticising it",
"The moon has a large concave circle on its face, it has a light side, it has a dark side, and it's no moon it's OUR moon, you know I'm starting to think George Lucas just straight up stole the story for Star Wars from our moon and obviously Seven Samurai",
"Do it, give in to the urge, turn your keyboard upside down and shake it over your food like its contents are a condiment",
"If you accidentally eat year old food and skin particles don't tell the ER it's because you shook your never cleaned keyboard over your dinner just to see what it'd taste like",
"The easiest way to remember which bracket is 'less than' is to imagine turning the < key 45 degrees counter-clockwise, and then it's an L. Big Programming doesn't want you to know this",
"All that poop coming out of your anus, so much poop that it's making you famous",
"Did you even ask the grass if it wanted to be touched",
"If you ordered something Next Day Delivery and then it didn't arrive, are you sure you're not just reliving the previous day?",
"If it involves mayonaise, gelatin, or anything sweet, it's not a salad and get out of the Mid-West USA ASAP",
"Imagine if you had to get a plaster cast every time you broke a tooth, having this wet plaster in your mouth for 6 weeks, wouldn't that be gross?",
"Did you know your keyboard's letters are in that order because the factory printed them that way?",
"It is better to underpromise and overdeliver but what's in the middle of those two?",
"Don't look, but it's behind you, no don't look, it will know",
"Do you ever wonder what the total word count of your life will be? And how the editor of your autobiography will hate you because you just couldn't stop yapping?",
"My biography will be cringed on true events",
"Those poor lonely variables, I can't believe a comma came in and seperated them",
"Everything you create of value will be stolen by an LLM and recycled back at someone without crediting you, so be sure to only make things which are incredibly gross",
"When you have no good ideas simply write down whatever comes to mind to remind yourself that yes, you have no good ideas",
"When a friend asks you to do them a favour that you know is important, never forget to",
"how do i get cowboy paint off a dog.",
"Welcome to the citadel of eternal wisdom. Behold, this crystal contains the sum of all human knowledge -- Except Rap And Country.",
"fuck 'jokes'. everything i tweet is real. raw insight without the horse shit. no, i will NOT follow trolls. twitter dot com. i live for this ",
"'Is Wario A Libertarian' - the greatest thread in the history of forums, locked by a moderator after 12,239 pages of heated debate,",
"see this watch? i got it by Crying. my car? crying. my beautiful wife? Crying. My perfect teeth? Crying. now get the fuck out of my office ",
"another day volunteering at the betsy ross museum. everyone keeps asking me if they can fuck the flag. buddy, they wont even let me fuck it",
"how come a baby born with a foot in its brain is considered a 'Miracle Baby' but when I get my dick stuck in a drawer im just some asshole ",
"'jail isnt real,' i assure myself as i close my eyes and ram the hallmark gift shop with my shitty bronco",
"THE COP GROWLS 'TAKE OFF TH OSE JEANS, CITIZEN.' I COMPLY, REVEALING THE FULL LENGTH DENIM TATTOOS ON BOTH LEGS. THE COP SCREAMS; DEFEATED",
"the doctor reveals my blood pressure is 420 over 69. i hoot & holler outta the building while a bunch of losers try to tell me that im dying ",
"strongest blade in the world, however, it is so fragile as to shatter when handled by any force other than the delicate touch of a lesbian .",
"who the fuck is scraeming 'LOG OFF' at my house. show yourself, coward. i will never log off ",
"IF THE ZOO BANS ME FOR HOLLERING AT THE ANIMALS I WILL FACE GOD AND WALK BACKWARDS INTO HELL",
"'This Whole Thing Smacks Of Gender,' i holler as i overturn my uncle's barbeque grill and turn the 4th of July into the 4th of Shit",
"my disrespectful teen son somehow got hold of a gluten product and now he wants to become a cat girl ",
"if your grave doesnt say 'rest in peace' on it you are automatically drafted into the skeleton war",
"its the weekend baby. youknow what that means. its time to drink precisely one beer and call 911",
"awfully bold of you to fly the Good Year blimp on a year that has been extremely bad thus far",
"the jduge orders me to take off my anonymous v mask & im wearing the joker makeup underneath it. everyone in the courtroom groans at my shit",
"so long suckers! i rev up my motorcylce and create a huge cloud of smoke. when the cloud dissipates im lying completely dead on the pavement ",
"the human mind... perhaps the most powerful weapon. second only to the 'GUN'",
"people come up to me and say, 'I will never use the bathroom. I will never shit' and i gotta tell them pal, sooner or later youre gonna shit",
"go ahead. keep screaming 'Shut The Fuck Up ' at me. it only makes my opinions Worse ",
"the worst part of nationalism is having to pretend the flag is really good, like 'yeah the country looks exactly like that. they nailed it' ",
"Twitter, as I understand it, is a sort of 'Hell' that I was banished to upon death in my previous life.",
"Fake children, real treasure!"
]

endnumber = len(phraselist)
randomnumber = random.randint(0, endnumber-1)

print(phraselist[randomnumber])

